name: Update README

on:
  push:
  pull_request:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate README.md
        uses: WiseNat/profile-readme@patch-1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: WiseNat
          template: "TEMPLATE.md"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coauthor_email: WiseNat@users.noreply.github.com
          coauthor_name: WiseNat
